### ISSUE TITLE
공지 API

### ISSUE THREAD

**Issue by BeLeap** [KU-KUICS/KUICS_backend#15]
- [ ] GET host/api/notice: 공지 전체보기
- [ ] GET host/api/notice/:notice_id 공지 상세보기
- [ ] POST host/api/notice/:notice_id/comment: 공지 댓글 쓰기
- [ ] PUT host/api/notice/:notice_id/comment/:comment_id: 공지 댓글 수정
- [ ] DELETE host/api/notice/:notice_id/comment/:comment_id: 공지 댓글 삭제

**Comment by lsjbh45** [comment]
notice API 관련 결정할 사항 [일부 구현](https://github.com/KU-KUICS/KUICS_backend/tree/feature/%2315/notice)
- [ ] 추가해야 할 API 목록 확정 (post, revise, delete 이외에 getList, get, comment, recommend 등도 따로 구현할 것인지)
- [ ] board API와의 관계 고려 (따로 구현한다면 type에 맞는 것만 접근하도록 validation 필요)
- [ ] 추가할 위치 결정 (api/admin/notice 또는 api/notice)
- [ ] 분리한 validation, fuction 작성 위치 결정 (lib 또는 api)
- [ ] 어느 정도까지 분리해 작성할 것인지 (전체 분리해 type만 넘기거나, validation은 각자 처리하고 기능만 호출하도록)

**Comment by BeLeap** [comment]
난
1번 post, revise, delete 만 따로 만드는게 맞는거 같고
2번은 뭔소린지 정확히 이해 못하겠다만 내가 말한식으로 구현하면 되지 싶고
3번은 api/admin/notice가 맞는거 같고
4번은 api에서 하드코딩하는게 맞다고 보고
5번은 api에서 처리하고 기능만 호출하는게 안전하다고 생각함(뭐 인풋 xss 처리 정도는 lib에서 해도 될듯)
